version: '3'

services:
  wireguard-client:
    image: linuxserver/wireguard
    container_name: wireguard-client
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config/wg0.conf:/config/wg0.conf:ro
      - /lib/modules:/lib/modules
    # when use host network cannot set sysctl
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
