version: '3'

networks:
  default:
    external: true
    name: ${DOCKER_BRIDGE}

services:
  ghost:
    image: ghost:4.41.3
    container_name: ghost
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      # url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ./content:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`ghost.${DOMAIN}`)"
      - "traefik.http.routers.ghost.entrypoints=https"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.routers.ghost.tls.certresolver=staging"
      - "traefik.http.routers.ghost.service=ghost-service"
      - "traefik.http.services.ghost-service.loadbalancer.server.port=2368"
  ghost-db:
    image: mysql:8
    container_name: ghost-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
    volumes:
      - ./mysql:/var/lib/mysql
