version: '3'

networks:
  default:
    external:
      name: main # Define by wireguard

services:
  wordpress:
    image: wordpress:5.9.2
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./www:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wp.domain.com`)"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=staging"
      - "traefik.http.routers.wordpress.service=wordpress-service"
      - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"
  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql:/var/lib/mysql
