version: "3"

networks:
  default:
    external:
      name: main

services:
  www:
    image: nginx
    container_name: www
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wwww.rule=Host(`your-domain.com`)'
      - 'traefik.http.routers.wwww.entrypoints=websecure'
      - 'traefik.http.routers.wwww.tls=true'
