version: "3"

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  www:
    image: nginx
    container_name: www
    restart: always
    expose:
      - "80"
    volumes:
      - .:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.www.entrypoints=https"
      - "traefik.http.routers.www.tls=true"
      - "traefik.http.routers.www.tls.certresolver=staging"
