version: '3'

networks:
  default:
    external:
      name: main

services:
  www:
    image: nginx
    container_name: www
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.wwww.rule=Host(`yourdomain.com`)
      - traefik.http.routers.wwww.entrypoints=https
      - traefik.http.routers.wwww.tls=true
      - traefik.http.routers.wwww.tls.certresolver=staging
