version: '3'

networks:
  default:
    external:
      name: main # Define by wireguard

services:
  www:
    image: nginx
    container_name: www
    restart: always
    volumes:
      - .:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wwww.rule=Host(`domain.com`)"
      - "traefik.http.routers.wwww.entrypoints=https"
      - "traefik.http.routers.wwww.tls=true"
      - "traefik.http.routers.wwww.tls.certresolver=staging"
