version: "3"

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}
services:
  minio:
    image: minio/minio:RELEASE.2022-06-17T02-00-35Z
    container_name: minio
    restart: always
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"
