version: "3"

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  vault:
    image: hashicorp/vault:1.8.1
    container_name: vault
    restart: always
    expose:
      - "8200"
    cap_add:
      - IPC_LOCK
    volumes:
     - ./vault/policy.json:/vault/policies/policy.json
