version: "3"

networks:
  default:
    external:
      name: main

volumes:
  mysql:
    driver: local

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
