version: "3"

networks:
  default:
    external:
      name: main

services:
  gitea:
    image: gitea/gitea:1.16.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=root
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`yourdomain.com`)
      - traefik.http.routers.gitea.entrypoints=https
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=staging
      - traefik.tcp.routers.giteassh.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteassh.tls=true
      - traefik.tcp.routers.giteassh.tls.certresolver=staging
      - traefik.tcp.routers.giteassh.entrypoints=ssh
      - traefik.tcp.routers.giteassh.service=giteassh
      - traefik.tcp.services.giteassh.loadbalancer.server.port=22
  db:
    image: mysql:8
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql
