version: "3"

networks:
  default:
    external: true
    name: ${DOCKER_BRIDGE}
services:
  consul:
    image: hashicorp/consul:1.11.2
    container_name: consul
    restart: always
    expose:
      - "8500"
      - "8600"
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    environment:
      - CONSUL_TOKEN=${CONSUL_TOKEN:-$$(cat /proc/sys/kernel/random/uuid)}
    entrypoint: "/bin/sh -c"
    command: |
      'sh -exs <<EOF
      mkdir -p consul/config
      if [ ! -f /consul/config/acl.hcl ]; then
          cat <<EON >/consul/config/acl.hcl
      acl {
          enabled = true
          default_policy = "deny"
          enable_token_persistence = true
          tokens {
              agent = "<uuid>"
              master = "<uuid>"
          }
      }
      EON
          sed -i "s/<uuid>/$${CONSUL_TOKEN}/g" /consul/config/acl.hcl
      fi
      /usr/local/bin/docker-entrypoint.sh agent -node=server-1 -server -ui -bootstrap-expect=1 -client=0.0.0.0
      EOF'
