version: '3'

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  dnsmasq:
    image: strm/dnsmasq
    container_name: dnsmasq
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "5300:53/udp"
