version: "3"

networks:
  default:
    external: true
    name: ${DOCKER_BRIDGE}

services:
  zentao:
    image: idoop/zentao:11.4.1
    container_name: zentao
    restart: always
    expose:
      - "80"
      - "3306"
    # mysql root account default password is '123456'.
    # the zentao adminstrator account is 'admin',and init password is '123456'.
    environment:
      # specifies Adminer account and password for web login database.
      ADMINER_USER: "root"
      ADMINER_PASSWD: "123456"
      BIND_ADDRESS: "false"
    volumes:
      - ./data:/opt/zbox/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zentao.rule=Host(`zentao.${DOMAIN}`)"
      - "traefik.http.routers.zentao.entrypoints=https"
      - "traefik.http.routers.zentao.tls=true"
      - "traefik.http.routers.zentao.tls.certresolver=staging"
      - "traefik.http.routers.zentao.service=zentao-service"
      - "traefik.http.services.zentao-service.loadbalancer.server.port=80"
