version: '3'

services:
  coredns:
    image: hydrz/coredns
    container_name: coredns
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - './config:/app/config/coredns'
      - '/tmp:/tmp'
