# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env
# docker-compose up -d
# docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'

networks:
  default:
    external:
      name: br0

services:
  dockovpn:
    image: alekslitvinenk/openvpn
    container_name: dockovpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
    environment:
      HOST_ADDR: ${HOST_ADDR}
    volumes:
      - ./config:/doc/Dockovpn
