version: '3'

networks:
  default:
    external:
      name: br0

services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
