version: "3"

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
