version: "3"

networks:
  default:
    external:
      name: br0

services:
  kutt:
    image: kutt/kutt
    container_name: kutt
    restart: always
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      SITE_NAME: URL Shortener
      DEFAULT_DOMAIN: kutt.${DOMAIN}
      ADMIN_EMAILS: admin@sraph.com
      CUSTOM_DOMAIN_USE_HTTPS: false
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: smtp.exmail.qq.com
      MAIL_PORT: 465
      MAIL_USER: ${EMAIL}
      MAIL_PASSWORD: ${EMAIL_PASSWORD}
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "start"
      ]
    ports:
      - "3000:3000"

  redis:
    image: redis:6.0-alpine

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kutt
    volumes:
      - ./postgres:/var/lib/postgresql/data
