version: "3"

networks:
  default:
    external: true
    name: ${DOCKER_BRIDGE}

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v20.2
    container_name: cockroach
    restart: always
    expose:
      - "8080"
      - "26257"
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    volumes:
      - ./cockroach:/var/lib/cockroach
