version: '3'

networks:
  default:
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.public.rule=Host(`your-domain.com`)'
      - 'traefik.http.routers.public.entrypoints=websecure'
      - 'traefik.http.routers.public.tls=true'
