version: '3'

networks:
  default:
    external:
      name: main

services:
  etcd:
    image: docker.io/bitnami/etcd:3.4
    container_name: redis
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - ./etcd:/bitnami/etcd
