version: "3"

networks:
  default:
    external: true
    name: ${DOCKER_BRIDGE}

services:
  mongo:
    image: mongo:5.0.7
    container_name: mongo
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
