version: '3'

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  mongo:
    image: bitnami/mongodb:5.0.7
    container_name: mongo
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/bitnami/mongodb
