version: '3'

networks:
  default:
    external: true
    name: ${DOKCER_BRIDGE}

services:
  mongo:
    image: mongo:5.0.7
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
